//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_default : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean InteractUI
        {
            get
            {
                return SteamVR_Actions.default_InteractUI;
            }
        }
        
        public virtual SteamVR_Action_Boolean Teleport
        {
            get
            {
                return SteamVR_Actions.default_Teleport;
            }
        }
        
        public virtual SteamVR_Action_Boolean GrabPinch
        {
            get
            {
                return SteamVR_Actions.default_GrabPinch;
            }
        }
        
        public virtual SteamVR_Action_Boolean GrabGrip
        {
            get
            {
                return SteamVR_Actions.default_GrabGrip;
            }
        }
        
        public virtual SteamVR_Action_Pose Pose
        {
            get
            {
                return SteamVR_Actions.default_Pose;
            }
        }
        
        public virtual SteamVR_Action_Skeleton SkeletonLeftHand
        {
            get
            {
                return SteamVR_Actions.default_SkeletonLeftHand;
            }
        }
        
        public virtual SteamVR_Action_Skeleton SkeletonRightHand
        {
            get
            {
                return SteamVR_Actions.default_SkeletonRightHand;
            }
        }
        
        public virtual SteamVR_Action_Single Squeeze
        {
            get
            {
                return SteamVR_Actions.default_Squeeze;
            }
        }
        
        public virtual SteamVR_Action_Boolean HeadsetOnHead
        {
            get
            {
                return SteamVR_Actions.default_HeadsetOnHead;
            }
        }
        
        public virtual SteamVR_Action_Boolean SnapTurnLeft
        {
            get
            {
                return SteamVR_Actions.default_SnapTurnLeft;
            }
        }
        
        public virtual SteamVR_Action_Boolean SnapTurnRight
        {
            get
            {
                return SteamVR_Actions.default_SnapTurnRight;
            }
        }
        
        public virtual SteamVR_Action_Boolean GrabMachine
        {
            get
            {
                return SteamVR_Actions.default_GrabMachine;
            }
        }
        
        public virtual SteamVR_Action_Boolean RotateHoraire
        {
            get
            {
                return SteamVR_Actions.default_RotateHoraire;
            }
        }
        
        public virtual SteamVR_Action_Boolean RotateAntiHoraire
        {
            get
            {
                return SteamVR_Actions.default_RotateAntiHoraire;
            }
        }
        
        public virtual SteamVR_Action_Boolean PullMachine
        {
            get
            {
                return SteamVR_Actions.default_PullMachine;
            }
        }
        
        public virtual SteamVR_Action_Boolean PushMachine
        {
            get
            {
                return SteamVR_Actions.default_PushMachine;
            }
        }
        
        public virtual SteamVR_Action_Boolean InterfaceOpening
        {
            get
            {
                return SteamVR_Actions.default_InterfaceOpening;
            }
        }
        
        public virtual SteamVR_Action_Boolean ValidateAction
        {
            get
            {
                return SteamVR_Actions.default_ValidateAction;
            }
        }
        
        public virtual SteamVR_Action_Boolean SelectOptionTop
        {
            get
            {
                return SteamVR_Actions.default_SelectOptionTop;
            }
        }
        
        public virtual SteamVR_Action_Boolean SelectOptionBot
        {
            get
            {
                return SteamVR_Actions.default_SelectOptionBot;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptic
        {
            get
            {
                return SteamVR_Actions.default_Haptic;
            }
        }
    }
}
